spring.application.name=daySeven


spring.datasource.url=jdbc:postgresql://localhost:5432/tasksix
spring.datasource.username=postgres
spring.datasource.password=2013

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379